import type { LevelDef } from "@/types/overflowing-palette";

export const easyLevels: LevelDef[] = [
  {
    id: 1,
    moves: 1,
    target: "blue",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 2,
    moves: 1,
    target: "red",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 3,
    moves: 1,
    target: "green",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "green", "green", "green", "green", "red", "red"],
      ["red", "red", "green", "green", "green", "green", "red", "red"],
      ["red", "red", "green", "green", "green", "green", "red", "red"],
      ["red", "red", "green", "green", "green", "green", "red", "red"],
      ["red", "red", "green", "green", "green", "green", "red", "red"],
      ["red", "red", "green", "green", "green", "green", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 4,
    moves: 1,
    target: "blue",
    grid: [
      ["blue", "blue", "blue", "blue", "green", "green", "green", "green"],
      ["blue", "blue", "blue", "blue", "green", "green", "green", "green"],
      ["blue", "blue", "blue", "blue", "green", "green", "green", "green"],
      ["blue", "blue", "blue", "blue", "green", "green", "green", "green"],
      ["blue", "blue", "blue", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "blue", "blue", "blue"],
      ["green", "green", "green", "green", "blue", "blue", "blue", "blue"],
      ["green", "green", "green", "green", "blue", "blue", "blue", "blue"],
      ["green", "green", "green", "green", "blue", "blue", "blue", "blue"],
      ["green", "green", "green", "green", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 5,
    moves: 1,
    target: "red",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 6,
    moves: 1,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "red", "red", "red"],
      ["green", "green", "green", "green", "red", "red", "red", "red"],
      ["green", "green", "green", "red", "red", "red", "red", "red"],
      ["green", "green", "red", "red", "red", "red", "red", "red"],
      ["green", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "green"],
      ["red", "red", "red", "red", "red", "red", "green", "green"],
      ["red", "red", "red", "red", "red", "green", "green", "green"],
      ["red", "red", "red", "red", "green", "green", "green", "green"],
      ["red", "red", "red", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 7,
    moves: 1,
    target: "blue",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "blue", "blue", "green", "green", "blue", "blue", "green"],
      ["green", "blue", "blue", "green", "green", "blue", "blue", "green"],
      ["green", "blue", "blue", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "blue", "blue", "green"],
      ["green", "blue", "blue", "green", "green", "blue", "blue", "green"],
      ["green", "blue", "blue", "green", "green", "blue", "blue", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 8,
    moves: 1,
    target: "red",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["red", "red", "red", "blue", "blue", "red", "red", "red"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["red", "red", "red", "blue", "blue", "red", "red", "red"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["red", "red", "red", "blue", "blue", "red", "red", "red"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["red", "red", "red", "blue", "blue", "red", "red", "red"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 9,
    moves: 1,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "green", "green", "green", "green", "green", "red", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "red", "green", "green", "green", "green", "red", "green"],
      ["green", "red", "green", "green", "green", "green", "red", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "red", "green", "green", "green", "green", "green", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 10,
    moves: 1,
    target: "blue",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 11,
    moves: 2,
    target: "red",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "green", "green", "green", "green", "green", "green", "red"],
      ["red", "green", "green", "green", "green", "green", "green", "red"],
      ["red", "green", "green", "green", "green", "green", "green", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 12,
    moves: 2,
    target: "green",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "red", "red", "red", "red", "blue", "blue"],
      ["red", "red", "red", "green", "green", "red", "red", "red"],
      ["red", "red", "red", "green", "green", "red", "red", "red"],
      ["blue", "blue", "red", "red", "red", "red", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 13,
    moves: 2,
    target: "blue",
    grid: [
      ["blue", "red", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "red", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "red", "red", "red", "red", "red", "blue", "blue"],
      ["blue", "red", "green", "red", "red", "red", "blue", "blue"],
      ["blue", "blue", "green", "blue", "blue", "red", "blue", "blue"],
      ["blue", "blue", "green", "blue", "blue", "red", "blue", "blue"],
      ["blue", "blue", "green", "green", "green", "red", "green", "blue"],
      ["blue", "blue", "green", "green", "green", "green", "green", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "green", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "green", "blue"],
    ],
  },
  {
    id: 14,
    moves: 2,
    target: "red",
    grid: [
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "blue", "red", "red", "red", "red", "blue", "blue"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["blue", "blue", "red", "red", "red", "red", "blue", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
    ],
  },
  {
    id: 15,
    moves: 2,
    target: "green",
    grid: [
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
    ],
  },
  {
    id: 16,
    moves: 2,
    target: "blue",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "green", "green", "red", "red", "green", "green", "red"],
      ["red", "green", "red", "red", "red", "red", "green", "red"],
      ["red", "green", "red", "green", "green", "red", "green", "red"],
      ["red", "red", "red", "green", "green", "red", "red", "red"],
      ["red", "red", "red", "green", "green", "red", "red", "red"],
      ["red", "green", "red", "green", "green", "red", "green", "red"],
      ["red", "green", "red", "red", "red", "red", "green", "red"],
      ["red", "green", "green", "red", "red", "green", "green", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 17,
    moves: 2,
    target: "red",
    grid: [
      ["red", "red", "red", "red", "red", "blue", "blue", "green"],
      ["red", "red", "red", "red", "blue", "blue", "green", "green"],
      ["red", "red", "red", "blue", "blue", "green", "green", "green"],
      ["red", "red", "blue", "blue", "green", "green", "green", "blue"],
      ["red", "blue", "blue", "green", "green", "green", "blue", "blue"],
      ["blue", "blue", "green", "green", "green", "blue", "blue", "red"],
      ["blue", "green", "green", "green", "blue", "blue", "red", "red"],
      ["green", "green", "green", "blue", "blue", "red", "red", "red"],
      ["green", "green", "blue", "blue", "red", "red", "red", "red"],
      ["green", "blue", "blue", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 18,
    moves: 2,
    target: "green",
    grid: [
      ["green", "red", "red", "green", "green", "red", "red", "green"],
      ["green", "red", "red", "green", "green", "red", "red", "green"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["green", "red", "red", "green", "green", "red", "red", "green"],
      ["green", "red", "red", "green", "green", "red", "red", "green"],
    ],
  },
  {
    id: 19,
    moves: 2,
    target: "blue",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 20,
    moves: 2,
    target: "red",
    grid: [
      ["red", "red", "blue", "red", "red", "blue", "red", "red"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["blue", "blue", "green", "green", "green", "green", "blue", "blue"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["blue", "blue", "green", "green", "green", "green", "blue", "blue"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["red", "red", "blue", "red", "red", "blue", "red", "red"],
    ],
  },
  {
    id: 21,
    moves: 3,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "blue", "red", "blue", "blue", "red", "blue", "green"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "blue", "blue", "blue", "blue", "blue", "blue", "green"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["green", "blue", "red", "blue", "blue", "red", "blue", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 22,
    moves: 3,
    target: "blue",
    grid: [
      ["red", "red", "red", "blue", "blue", "red", "red", "red"],
      ["red", "green", "blue", "blue", "blue", "blue", "green", "red"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["blue", "blue", "green", "red", "red", "green", "blue", "blue"],
      ["blue", "blue", "red", "green", "green", "red", "blue", "blue"],
      ["blue", "blue", "red", "green", "green", "red", "blue", "blue"],
      ["blue", "blue", "green", "red", "red", "green", "blue", "blue"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["red", "green", "blue", "blue", "blue", "blue", "green", "red"],
      ["red", "red", "red", "blue", "blue", "red", "red", "red"],
    ],
  },
  {
    id: 23,
    moves: 3,
    target: "red",
    grid: [
      ["red", "green", "green", "green", "green", "green", "green", "red"],
      ["green", "green", "blue", "green", "green", "blue", "green", "green"],
      ["green", "blue", "blue", "red", "red", "blue", "blue", "green"],
      ["red", "blue", "red", "red", "red", "red", "blue", "red"],
      ["red", "blue", "red", "red", "red", "red", "blue", "red"],
      ["red", "blue", "red", "red", "red", "red", "blue", "red"],
      ["red", "blue", "red", "red", "red", "red", "blue", "red"],
      ["red", "green", "green", "red", "red", "green", "green", "red"],
      ["red", "green", "blue", "blue", "blue", "blue", "green", "red"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
    ],
  },
  {
    id: 24,
    moves: 3,
    target: "green",
    grid: [
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
      ["red", "red", "blue", "blue", "blue", "blue", "red", "red"],
      ["red", "blue", "blue", "red", "red", "blue", "blue", "red"],
      ["green", "blue", "red", "red", "red", "red", "blue", "green"],
      ["green", "blue", "red", "blue", "blue", "red", "blue", "green"],
      ["green", "blue", "red", "blue", "blue", "red", "blue", "green"],
      ["green", "blue", "red", "red", "red", "red", "blue", "green"],
      ["red", "blue", "blue", "red", "red", "blue", "blue", "red"],
      ["red", "red", "blue", "blue", "blue", "blue", "red", "red"],
      ["green", "red", "green", "blue", "blue", "green", "red", "green"],
    ],
  },
  {
    id: 25,
    moves: 3,
    target: "blue",
    grid: [
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
      ["red", "green", "red", "blue", "blue", "red", "green", "red"],
      ["blue", "red", "green", "blue", "blue", "green", "red", "blue"],
      ["blue", "green", "blue", "blue", "blue", "blue", "green", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["blue", "green", "blue", "blue", "blue", "blue", "green", "blue"],
      ["blue", "red", "green", "blue", "blue", "green", "red", "blue"],
      ["red", "green", "red", "blue", "blue", "red", "green", "red"],
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
    ],
  },
  {
    id: 26,
    moves: 3,
    target: "red",
    grid: [
      ["red", "blue", "green", "green", "green", "green", "blue", "red"],
      ["blue", "blue", "red", "green", "green", "red", "blue", "blue"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
      ["green", "red", "blue", "red", "red", "blue", "red", "green"],
      ["green", "red", "blue", "red", "red", "blue", "red", "green"],
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["blue", "blue", "red", "green", "green", "red", "blue", "green"],
      ["red", "blue", "green", "green", "green", "green", "blue", "red"],
    ],
  },
  {
    id: 27,
    moves: 3,
    target: "green",
    grid: [
      ["red", "blue", "blue", "green", "green", "blue", "blue", "red"],
      ["red", "red", "blue", "green", "green", "blue", "red", "red"],
      ["green", "green", "blue", "blue", "blue", "blue", "green", "green"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["red", "red", "blue", "blue", "blue", "blue", "red", "red"],
      ["red", "blue", "blue", "green", "green", "blue", "blue", "red"],
      ["green", "blue", "green", "green", "green", "green", "blue", "green"],
      ["green", "red", "green", "green", "green", "green", "red", "green"],
      ["red", "red", "red", "green", "green", "red", "red", "red"],
      ["blue", "blue", "red", "red", "red", "red", "blue", "blue"],
    ],
  },
  {
    id: 28,
    moves: 3,
    target: "blue",
    grid: [
      ["green", "red", "red", "red", "red", "green", "green", "green"],
      ["green", "red", "blue", "blue", "red", "green", "blue", "green"],
      ["green", "red", "red", "red", "red", "green", "blue", "green"],
      ["green", "green", "red", "green", "green", "green", "green", "green"],
      ["blue", "blue", "red", "blue", "blue", "red", "red", "red"],
      ["red", "red", "red", "blue", "blue", "red", "blue", "blue"],
      ["green", "green", "green", "green", "green", "red", "green", "green"],
      ["green", "blue", "green", "red", "red", "red", "red", "green"],
      ["green", "blue", "green", "red", "blue", "blue", "red", "green"],
      ["green", "green", "green", "red", "red", "red", "red", "green"],
    ],
  },
  {
    id: 29,
    moves: 3,
    target: "red",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["blue", "blue", "green", "blue", "blue", "green", "blue", "blue"],
      ["red", "blue", "blue", "red", "red", "blue", "blue", "red"],
      ["red", "red", "blue", "red", "red", "blue", "red", "red"],
      ["green", "blue", "red", "red", "red", "red", "blue", "green"],
      ["green", "blue", "red", "red", "red", "red", "blue", "green"],
      ["red", "red", "blue", "red", "red", "blue", "red", "red"],
      ["red", "blue", "blue", "red", "red", "blue", "blue", "red"],
      ["blue", "blue", "green", "blue", "blue", "green", "blue", "blue"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 30,
    moves: 3,
    target: "green",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "red", "blue", "green"],
      ["blue", "green", "red", "red", "blue", "blue", "red", "blue"],
      ["blue", "red", "green", "blue", "red", "blue", "blue", "red"],
      ["blue", "red", "green", "green", "blue", "red", "blue", "blue"],
      ["blue", "red", "green", "green", "green", "blue", "red", "blue"],
      ["blue", "red", "blue", "green", "green", "green", "red", "blue"],
      ["blue", "blue", "red", "blue", "green", "green", "red", "blue"],
      ["red", "blue", "blue", "red", "blue", "green", "red", "blue"],
      ["blue", "red", "blue", "blue", "red", "red", "green", "blue"],
      ["green", "blue", "red", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 31,
    moves: 4,
    target: "blue",
    grid: [
      ["blue", "green", "green", "red", "green", "red", "red", "blue"],
      ["blue", "red", "red", "red", "green", "green", "green", "blue"],
      ["green", "green", "green", "blue", "blue", "red", "green", "blue"],
      ["red", "red", "blue", "blue", "blue", "red", "green", "blue"],
      ["green", "green", "blue", "blue", "blue", "red", "green", "red"],
      ["red", "green", "red", "blue", "blue", "blue", "green", "green"],
      ["blue", "green", "red", "blue", "blue", "blue", "red", "red"],
      ["blue", "green", "red", "blue", "blue", "green", "green", "green"],
      ["blue", "green", "green", "green", "red", "red", "red", "blue"],
      ["blue", "red", "red", "green", "red", "green", "green", "blue"],
    ],
  },
  {
    id: 32,
    moves: 4,
    target: "red",
    grid: [
      ["green", "green", "green", "red", "red", "green", "green", "green"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["green", "green", "blue", "red", "red", "blue", "green", "green"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["green", "green", "green", "blue", "blue", "green", "green", "green"],
      ["blue", "blue", "green", "red", "red", "green", "blue", "blue"],
      ["green", "green", "green", "red", "red", "green", "green", "green"],
      ["blue", "blue", "blue", "green", "green", "blue", "blue", "blue"],
      ["green", "red", "blue", "red", "red", "blue", "red", "green"],
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
    ],
  },
  {
    id: 33,
    moves: 4,
    target: "green",
    grid: [
      ["blue", "blue", "blue", "green", "green", "blue", "blue", "blue"],
      ["green", "red", "red", "green", "green", "red", "red", "green"],
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["blue", "blue", "blue", "red", "red", "blue", "blue", "blue"],
      ["green", "red", "blue", "blue", "blue", "blue", "red", "green"],
      ["green", "red", "red", "green", "green", "red", "red", "green"],
      ["blue", "blue", "blue", "green", "green", "blue", "blue", "blue"],
    ],
  },
  {
    id: 34,
    moves: 4,
    target: "blue",
    grid: [
      ["blue", "green", "green", "red", "red", "green", "green", "blue"],
      ["blue", "green", "blue", "red", "red", "blue", "green", "blue"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["blue", "green", "blue", "red", "red", "blue", "green", "blue"],
      ["blue", "green", "blue", "red", "red", "blue", "green", "blue"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["green", "red", "red", "blue", "blue", "red", "red", "green"],
      ["blue", "green", "blue", "red", "red", "blue", "green", "blue"],
      ["blue", "green", "green", "red", "red", "green", "green", "blue"],
    ],
  },
  {
    id: 35,
    moves: 4,
    target: "red",
    grid: [
      ["red", "blue", "green", "blue", "blue", "green", "blue", "red"],
      ["blue", "red", "green", "blue", "blue", "green", "red", "blue"],
      ["blue", "green", "blue", "blue", "blue", "blue", "green", "blue"],
      ["red", "blue", "blue", "red", "red", "blue", "blue", "red"],
      ["green", "blue", "red", "red", "red", "red", "blue", "green"],
      ["green", "red", "red", "green", "green", "red", "red", "green"],
      ["green", "blue", "blue", "red", "red", "blue", "blue", "green"],
      ["blue", "green", "blue", "blue", "blue", "blue", "green", "blue"],
      ["blue", "red", "green", "blue", "blue", "green", "red", "blue"],
      ["red", "blue", "green", "blue", "blue", "green", "blue", "red"],
    ],
  },
  {
    id: 36,
    moves: 4,
    target: "green",
    grid: [
      ["red", "green", "red", "red", "red", "red", "green", "red"],
      ["red", "red", "green", "red", "red", "green", "red", "red"],
      ["blue", "blue", "red", "blue", "blue", "red", "blue", "blue"],
      ["red", "blue", "red", "green", "green", "red", "blue", "red"],
      ["green", "red", "blue", "red", "red", "blue", "red", "green"],
      ["red", "blue", "blue", "blue", "blue", "blue", "blue", "red"],
      ["green", "red", "blue", "red", "red", "blue", "red", "green"],
      ["green", "red", "blue", "red", "red", "blue", "red", "green"],
      ["blue", "red", "blue", "red", "red", "blue", "red", "blue"],
      ["blue", "blue", "red", "green", "green", "red", "blue", "blue"],
    ],
  },
  {
    id: 37,
    moves: 4,
    target: "blue",
    grid: [
      ["blue", "blue", "red", "green", "green", "green", "blue", "blue"],
      ["green", "red", "green", "red", "blue", "red", "green", "red"],
      ["green", "red", "green", "red", "blue", "red", "green", "red"],
      ["green", "red", "green", "red", "red", "red", "green", "blue"],
      ["blue", "red", "green", "green", "green", "green", "green", "blue"],
      ["blue", "red", "red", "red", "red", "red", "green", "blue"],
      ["blue", "red", "green", "green", "green", "red", "green", "red"],
      ["green", "red", "green", "blue", "green", "red", "green", "red"],
      ["green", "red", "green", "blue", "green", "red", "green", "red"],
      ["blue", "blue", "red", "red", "red", "green", "blue", "blue"],
    ],
  },
  {
    id: 38,
    moves: 4,
    target: "red",
    grid: [
      ["green", "blue", "blue", "green", "green", "green", "green", "blue"],
      ["blue", "blue", "red", "green", "blue", "blue", "green", "blue"],
      ["red", "green", "red", "red", "green", "blue", "blue", "red"],
      ["blue", "red", "red", "red", "green", "red", "red", "blue"],
      ["green", "blue", "green", "red", "red", "green", "blue", "green"],
      ["green", "blue", "green", "red", "red", "green", "blue", "green"],
      ["blue", "red", "red", "green", "red", "red", "red", "blue"],
      ["red", "blue", "blue", "green", "red", "red", "green", "red"],
      ["blue", "green", "blue", "blue", "green", "red", "blue", "blue"],
      ["blue", "green", "green", "green", "green", "blue", "blue", "green"],
    ],
  },
  {
    id: 39,
    moves: 4,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "red", "green", "blue"],
      ["green", "blue", "green", "green", "red", "green", "green", "green"],
      ["red", "blue", "blue", "red", "blue", "green", "blue", "green"],
      ["red", "green", "green", "blue", "red", "blue", "red", "green"],
      ["green", "green", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "green", "green"],
      ["green", "red", "blue", "red", "blue", "green", "green", "red"],
      ["green", "blue", "green", "blue", "red", "blue", "blue", "red"],
      ["green", "green", "green", "red", "green", "green", "blue", "green"],
      ["blue", "green", "red", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 40,
    moves: 4,
    target: "blue",
    grid: [
      ["green", "green", "red", "blue", "blue", "green", "red", "red"],
      ["blue", "red", "red", "green", "red", "green", "green", "blue"],
      ["blue", "red", "green", "green", "red", "red", "green", "blue"],
      ["green", "red", "red", "blue", "blue", "green", "green", "red"],
      ["green", "blue", "green", "green", "red", "red", "blue", "red"],
      ["blue", "green", "green", "blue", "blue", "red", "red", "blue"],
      ["green", "blue", "red", "blue", "blue", "green", "blue", "red"],
      ["green", "red", "red", "red", "green", "green", "green", "red"],
      ["blue", "red", "blue", "red", "green", "blue", "green", "blue"],
      ["green", "red", "green", "green", "red", "red", "green", "red"],
    ],
  },
  {
    id: 41,
    moves: 5,
    target: "red",
    grid: [
      ["green", "blue", "red", "green", "green", "red", "blue", "green"],
      ["red", "blue", "blue", "green", "green", "blue", "blue", "red"],
      ["red", "green", "blue", "blue", "blue", "blue", "green", "red"],
      ["red", "green", "red", "red", "red", "red", "green", "red"],
      ["blue", "red", "blue", "green", "green", "blue", "red", "blue"],
      ["blue", "green", "blue", "red", "red", "blue", "green", "blue"],
      ["red", "green", "red", "blue", "blue", "red", "green", "red"],
      ["green", "red", "red", "red", "red", "red", "red", "green"],
      ["red", "green", "red", "green", "green", "red", "green", "red"],
      ["red", "red", "blue", "red", "red", "blue", "red", "red"],
    ],
  },
  {
    id: 42,
    moves: 5,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 43,
    moves: 5,
    target: "blue",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 44,
    moves: 5,
    target: "red",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 45,
    moves: 5,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 46,
    moves: 5,
    target: "blue",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 47,
    moves: 5,
    target: "red",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
  {
    id: 48,
    moves: 5,
    target: "green",
    grid: [
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
      ["green", "green", "green", "green", "green", "green", "green", "green"],
    ],
  },
  {
    id: 49,
    moves: 5,
    target: "blue",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 50,
    moves: 5,
    target: "red",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
];
