import type { LevelDef } from "@/types/overflowing-palette";

export const mediumLevels: LevelDef[] = [
  {
    id: 1,
    moves: 2,
    target: "yellow",
    grid: [
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
      ["blue", "black", "black", "black", "black", "black", "black", "blue"],
      ["blue", "black", "blue", "blue", "blue", "blue", "black", "blue"],
      ["blue", "black", "blue", "blue", "blue", "blue", "black", "blue"],
      ["blue", "black", "blue", "blue", "blue", "blue", "black", "blue"],
      ["blue", "black", "blue", "blue", "blue", "blue", "black", "blue"],
      ["blue", "black", "blue", "blue", "blue", "blue", "black", "blue"],
      ["blue", "black", "blue", "blue", "blue", "blue", "black", "blue"],
      ["blue", "black", "black", "black", "black", "black", "black", "blue"],
      ["blue", "blue", "blue", "blue", "blue", "blue", "blue", "blue"],
    ],
  },
  {
    id: 2,
    moves: 3,
    target: "blue",
    grid: [
      ["green", "black", "green", "yellow", "yellow", "green", "black", "green"],
      ["green", "black", "green", "red", "red", "green", "black", "green"],
      ["yellow", "yellow", "red", "red", "red", "red", "yellow", "yellow"],
      ["black", "black", "red", "blue", "blue", "red", "black", "black"],
      ["yellow", "red", "red", "blue", "blue", "red", "red", "yellow"],
      ["yellow", "red", "red", "blue", "blue", "red", "red", "yellow"],
      ["black", "black", "red", "blue", "blue", "red", "black", "black"],
      ["yellow", "yellow", "red", "red", "red", "red", "yellow", "yellow"],
      ["green", "black", "green", "red", "red", "green", "black", "green"],
      ["green", "black", "green", "yellow", "yellow", "green", "black", "green"],
    ],
  },
  {
    id: 3,
    moves: 3,
    target: "red",
    grid: [
      ["red", "red", "yellow", "green", "green", "green", "green", "green"],
      ["red", "black", "yellow", "black", "black", "black", "black", "red"],
      ["red", "black", "yellow", "yellow", "yellow", "yellow", "black", "red"],
      ["red", "black", "blue", "blue", "blue", "blue", "black", "red"],
      ["red", "black", "blue", "yellow", "yellow", "blue", "black", "red"],
      ["red", "black", "blue", "yellow", "yellow", "blue", "black", "red"],
      ["red", "black", "blue", "blue", "blue", "blue", "black", "red"],
      ["red", "black", "yellow", "yellow", "yellow", "yellow", "black", "red"],
      ["red", "black", "black", "black", "black", "yellow", "black", "red"],
      ["green", "green", "green", "green", "green", "yellow", "red", "red"],
    ],
  },
  {
    id: 4,
    moves: 3,
    target: "green",
    grid: [
      ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
      ["blue", "green", "black", "green", "green", "black", "green", "blue"],
      ["blue", "black", "black", "green", "green", "black", "black", "blue"],
      ["blue", "blue", "black", "blue", "blue", "black", "blue", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "red", "red", "red", "red", "red", "red", "blue"],
      ["blue", "blue", "black", "blue", "blue", "black", "blue", "blue"],
      ["blue", "black", "black", "green", "green", "black", "black", "blue"],
      ["blue", "green", "black", "green", "green", "black", "green", "blue"],
      ["yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
    ],
  },
  {
    id: 5,
    moves: 3,
    target: "yellow",
    grid: [
      ["green", "green", "green", "red", "red", "black", "green", "green"],
      ["black", "black", "black", "red", "red", "black", "black", "green"],
      ["yellow", "yellow", "green", "red", "red", "blue", "blue", "blue"],
      ["yellow", "yellow", "green", "red", "red", "blue", "yellow", "yellow"],
      ["yellow", "yellow", "green", "red", "red", "black", "yellow", "yellow"],
      ["yellow", "yellow", "black", "red", "red", "green", "yellow", "yellow"],
      ["yellow", "yellow", "blue", "red", "red", "green", "yellow", "yellow"],
      ["blue", "blue", "blue", "red", "red", "green", "yellow", "yellow"],
      ["green", "black", "black", "red", "red", "black", "black", "black"],
      ["green", "green", "black", "red", "red", "green", "green", "green"],
    ],
  },
  {
    id: 6,
    moves: 3,
    target: "blue",
    grid: [
      ["black", "yellow", "black", "black", "red", "black", "red", "black"],
      ["green", "yellow", "green", "green", "green", "green", "green", "red"],
      ["green", "yellow", "blue", "blue", "red", "black", "green", "black"],
      ["green", "yellow", "blue", "red", "red", "red", "green", "red"],
      ["green", "yellow", "blue", "black", "black", "blue", "green", "yellow"],
      ["green", "yellow", "blue", "black", "black", "blue", "green", "yellow"],
      ["red", "yellow", "red", "red", "red", "blue", "green", "yellow"],
      ["black", "yellow", "black", "red", "blue", "blue", "green", "yellow"],
      ["red", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow", "yellow"],
      ["black", "red", "black", "red", "black", "black", "green", "black"],
    ],
  },
  {
    id: 7,
    moves: 3,
    target: "red",
    grid: [
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
      ["red", "red", "red", "red", "red", "red", "red", "red"],
    ],
  },
];
